### ISSUE TITLE
Sentiment Scores of Tweet Replies

### ISSUE THREAD

**Issue by jramtos** [advanced-ml-project/project#2]
- Get sentiment scores of replies_archive.zip (once cleaned)

**Comment by lokijoanderso** [comment]
So..... this is kinda of done.
The code is written.

Unfortunately, when cleaned tweet responses were matched with original tweets, the number of remaining records plummeted from 17,000 to 3,000.

I pulled a handful of tweets with no matching replies and examined them on twitter.
I'm not certain this isn't a coding error, but it doesn't seem to be...

I found three things definitely going on:
- Filtering to only English tweets and tweets that aren't only emojis drops the counts.
- There seems to be an issue with private vs public tweets, where the reply counts displayed on a tweet include private tweets, but only public tweets are pull-able and view-able in detail either online or in the browser.

Anyway. I'm currently pulling another month worth of tweets.
The count is way too small right now.

**Comment by lokijoanderso** [comment]
- [x]  alter sentiment score code to handle tweets
- [x] apply categories and category labels
- [x] pull additional tweets to increase record count

Outputs have consistent column names regardless of source:
- 'id'
- 'topic'
- 'source'
- 'text'
- 'replyCount'
- 'vaderMean'
- 'vaderStd'
- 'vaderCatLabel'
- 'vaderCat'

**Comment by lokijoanderso** [comment]
Found the match issue.

Apparently the vast majority of these comments are flagged as potentially offensive... 0_0
So I had to add (filter:safe or -filter:safe) to the pull to get all replies.
 
 Repulling all replies.

The format stuff will be the same as last push, though, so work can continue else where.

**Comment by lokijoanderso** [comment]
Final Counts:

Tweets = 20,697 
 - file name 'data/tweets_all.csv'
  - built off 34K original tweets filtered ones with 5 or more replies
  - a total of 1.3M replies scraped
  - March & April of 2021

Articles = 3,360
- file name 'data/articles_all.csv'
- built off 4,769 original articles filtered to ones with 5 or more replies
- a total of 917,736 replies
- January to March 2018

Both files have these columns:
 - 'id'
 - 'topic'
 -  'source'
 -  'text'
 -  'replyCount': for further filtering on count if desired
 -  'vaderMean'
 -  'vaderStd' - for standard target
 -  'vaderCatLabel': 'low', 'medium' or 'high' polarization
 -  'vaderCat' : 0, 1 or 2  - for Cohen's kappa target
