### ISSUE TITLE
Classification coding for high to low polarity

### ISSUE THREAD

**Issue by jramtos** [advanced-ml-project/project#3]
- [x] Creating a classification coding for high to low polarity with NYT comments
- [x] Creating a classification coding for high to low polarity with Tweet Replies

**Comment by lokijoanderso** [comment]
I decided to use an conceptual framework of "what would totally random responses look like" and "what would a bimodal distribution with modes at -1 and 1 look like" to define standard deviation categories. So they are the same for both data sets.
