### ISSUE TITLE
topic modeling updates

### ISSUE THREAD

**Issue by lokijoanderso** [advanced-ml-project/project#6]
- [x]  update topic modeling for tweet dataset
- [x]  update output columns for articles dataset

Output minimally needs:
For tweets:
- TweetId
- Username
- ConversationId
- Text
- Topic

For articles:
- articleID
- Snippet
- Topic

**Comment by jramtos** [comment]
Thank you Kelsey! 
I will work on this now :)

**Comment by jramtos** [comment]
For tweets:
data/tweets.csv

For articles:
data/articles.csv
